//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeOdevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanıcılar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanıcılar()
        {
            this.urunler = new HashSet<urunler>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string sifre { get; set; }
        public string adres { get; set; }
        public Nullable<long> kartNo { get; set; }
        public Nullable<int> ay { get; set; }
        public Nullable<int> yıl { get; set; }
        public Nullable<int> cvv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urunler> urunler { get; set; }
    }
}
