//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projeOdevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public int UrunId { get; set; }
        public Nullable<int> KullanıcıId { get; set; }
        public Nullable<int> Mama { get; set; }
        public Nullable<int> Oyuncak { get; set; }
        public Nullable<int> Aksesuar { get; set; }
        public string SiparisAdres { get; set; }
    
        public virtual kullanıcılar kullanıcılar { get; set; }
    }
}
